### PR TITLE
Fix printing negative constant literals

### LINKED ISSUE #1564: [hlsl/msl-out] incorrect output for expression containing double negation
Given the following WGSL program:

```
[[stage(compute), workgroup_size(1, 1, 1)]]
fn main() {
    let x = -(-1);
}
```

naga will produce the following:

HLSL:
```
[numthreads(1, 1, 1)]
void main()
{
    int x = --1;
}
```

MSL:
```
// language: metal1.1
#include <metal_stdlib>
#include <simd/simd.h>


kernel void main_(
) {
    int x = --1;
}
```

Note that the double negation has been turned into a pre-decrement.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #1564
Blocked on https://github.com/gfx-rs/rspirv/issues/227

There is some GLSL renamings going on, which are surprising to see.

### CODE REVIEW

**Review by jimblandy — APPROVED** [review]
This looks good to me, except for the changes to `tests/out/glsl/image.queries.*` - I can't see why those should be introduced by this PR.

**Comment by kvark** [comment]
Moved the tests to https://github.com/gfx-rs/naga/pull/1568, will need to rebase afterwards. We are blocked here anyway.

**Comment by teoxoy** [comment]
Looks like https://github.com/gfx-rs/rspirv/pull/231 landed, however there is no release yet.

**Comment by ErichDonGubler** [comment]
I'm trying to revive/unblock this (minus an upstream release from `rspirv`) at #2087, in case anybody is interested!

**Pull request closed without merging**
