### PR TITLE
[glsl-out] Add built-in functions to keywords

### LINKED ISSUE #2276: [glsl-out] Declaring a variable called "texture" leads to a translation error under certain conditions
This bug only happens when targeting glsl, present on naga v0.11.0 with wgpu.

The smallest reproducible example I've got:
```wgsl
struct VertexOutput {
    @builtin(position) pos : vec4<f32>,
    @location(0)       uv  : vec2<f32>,
}

// The group probably doesn't matter
@group(1) @binding(0) var t0: texture_2d<f32>;
@group(1) @binding(1) var s0: sampler;

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    // not sure if only textureSample triggers this bug
    let texture = textureSample(t0, s0, in.uv); // must be called texture
    let any_var = textureSample(t0, s0, in.uv); // ordering is important!

    // can be anything
    return vec4(1.0);
}
```

<details><summary>Error</summary>
<p>

```
 ERROR wgpu::backend::direct > Shader translation error for stage FRAGMENT: 0:32(17): error: no matching function for call to `texture(sampler2D, vec2)'; candidates are:
0:32(17): error:    vec4 texture(sampler1D, float)
0:32(17): error:    ivec4 texture(isampler1D, float)
0:32(17): error:    uvec4 texture(usampler1D, float)
0:32(17): error:    vec4 texture(sampler2D, vec2)
0:32(17): error:    ivec4 texture(isampler2D, vec2)
0:32(17): error:    uvec4 texture(usampler2D, vec2)
0:32(17): error:    vec4 texture(sampler3D, vec3)
0:32(17): error:    ivec4 texture(isampler3D, vec3)
0:32(17): error:    uvec4 texture(usampler3D, vec3)
0:32(17): error:    vec4 texture(samplerCube, vec3)
0:32(17): error:    ivec4 texture(isamplerCube, vec3)
0:32(17): error:    uvec4 texture(usamplerCube, vec3)
0:32(17): error:    float texture(sampler1DShadow, vec3)
0:32(17): error:    float texture(sampler2DShadow, vec3)
0:32(17): error:    float texture(samplerCubeShadow, vec4)
0:32(17): error:    vec4 texture(sampler1DArray, vec2)
0:32(17): error:    ivec4 texture(isampler1DArray, vec2)
0:32(17): error:    uvec4 texture(usampler1DArray, vec2)
0:32(17): error:    vec4 texture(sampler2DArray, vec3)
0:32(17): error:    ivec4 texture(isampler2DArray, vec3)
0:32(17): error:    uvec4 texture(usampler2DArray, vec3)
0:32(17): error:    vec4 texture(samplerCubeArray, vec4)
0:32(17): error:    ivec4 texture(isamplerCubeArray, vec4)
0:32(17): error:    uvec4 texture(usamplerCubeArray, vec4)
0:32(17): error:    float texture(sampler1DArrayShadow, vec3)
0:32(17): error:    float texture(sampler2DArrayShadow, vec4)
0:32(17): error:    float texture(samplerCubeArrayShadow, vec4, float)
0:32(17): error:    vec4 texture(sampler2DRect, vec2)
0:32(17): error:    ivec4 texture(isampler2DRect, vec2)
0:32(17): error:    uvec4 texture(usampler2DRect, vec2)
0:32(17): error:    float texture(sampler2DRectShadow, vec3)
0:32(17): error:    vec4 texture(sampler1D, float, float)
0:32(17): error:    ivec4 texture(isampler1D, float, float)
0:32(17): error:    uvec4 texture(usampler1D, float, float)
0:32(17): error:    vec4 texture(sampler2D, vec2, float)
0:32(17): error:    ivec4 texture(isampler2D, vec2, float)
0:32(17): error:    uvec4 texture(usampler2D, vec2, float)
0:32(17): error:    vec4 texture(sampler3D, vec3, float)
0:32(17): error:    ivec4 texture(isampler3D, vec3, float)
0:32(17): error:    uvec4 texture(usampler3D, vec3, float)
0:32(17): error:    vec4 texture(samplerCube, vec3, float)
0:32(17): error:    ivec4 texture(isamplerCube, vec3, float)
0:32(17): error:    uvec4 texture(usamplerCube, vec3, float)
0:32(17): error:    float texture(sampler1DShadow, vec3, float)
0:32(17): error:    float texture(sampler2DShadow, vec3, float)
0:32(17): error:    float texture(samplerCubeShadow, vec4, float)
0:32(17): error:    vec4 texture(sampler1DArray, vec2, float)
0:32(17): error:    ivec4 texture(isampler1DArray, vec2, float)
0:32(17): error:    uvec4 texture(usampler1DArray, vec2, float)
0:32(17): error:    vec4 texture(sampler2DArray, vec3, float)
0:32(17): error:    ivec4 texture(isampler2DArray, vec3, float)
0:32(17): error:    uvec4 texture(usampler2DArray, vec3, float)
0:32(17): error:    vec4 texture(samplerCubeArray, vec4, float)
0:32(17): error:    ivec4 texture(isamplerCubeArray, vec4, float)
0:32(17): error:    uvec4 texture(usamplerCubeArray, vec4, float)
0:32(17): error:    float texture(sampler1DArrayShadow, vec3, float)
0:32(17): error:    float texture(sampler2DArrayShadow, vec4)
0:32(17): error:    float texture(sampler2DArrayShadow, vec4, float)
0:32(17): error:    float texture(samplerCubeArrayShadow, vec4, float)
0:32(17): error:    float texture(samplerCubeArrayShadow, vec4, float, float)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by fornwall**
Add built-in functions to keywords. Fixes #2276 and part of #2366.

As the comment shows this is taken from https://dawn.googlesource.com/dawn/+/refs/heads/main/src/tint/lang/wgsl/ast/transform/renamer.cc#39 - is that ok? Any ideas for a reference of this?

List of removed keywords:
- `Rect`
- `uimage2DMSArraystruct`

List of added keywords:
- `abs`
- `acos`
- `acosh`
- `all`
- `any`
- `asin`
- `asinh`
- `atan`
- `atanh`
- `atomicAdd`
- `atomicAnd`
- `atomicCompSwap`
- `atomicCounter`
- `atomicCounterDecrement`
- `atomicCounterIncrement`
- `atomicExchange`
- `atomicMax`
- `atomicMin`
- `atomicOr`
- `atomicXor`
- `barrier`
- `bitCount`
- `bitfieldExtract`
- `bitfieldInsert`
- `bitfieldReverse`
- `ceil`
- `clamp`
- `cos`
- `cosh`
- `cross`
- `dFdx`
- `dFdy`
- `degrees`
- `determinant`
- `distance`
- `dot`
- `equal`
- `exp`
- `exp2`
- `faceforward`
- `findLSB`
- `findMSB`
- `floatBitsToInt`
- `floatBitsToUint`
- `floor`
- `fract`
- `frexp`
- `fwidth`
- `gl_BaseInstance`
- `gl_BaseVertex`
- `gl_ClipDistance`
- `gl_DepthRangeParameters`
- `gl_DrawID`
- `gl_FragCoord`
- `gl_FragDepth`
- `gl_FrontFacing`
- `gl_GlobalInvocationID`
- `gl_InstanceID`
- `gl_LocalInvocationID`
- `gl_LocalInvocationIndex`
- `gl_NumSamples`
- `gl_NumWorkGroups`
- `gl_PerVertex`
- `gl_PointCoord`
- `gl_PointSize`
- `gl_Position`
- `gl_PrimitiveID`
- `gl_SampleID`
- `gl_SampleMask`
- `gl_SampleMaskIn`
- `gl_SamplePosition`
- `gl_VertexID`
- `gl_WorkGroupID`
- `gl_WorkGroupSize`
- `greaterThan`
- `greaterThanEqual`
- `groupMemoryBarrier`
- `imageLoad`
- `imageSize`
- `imageStore`
- `imulExtended`
- `intBitsToFloat`
- `inverse`
- `inversesqrt`
- `isampler2DRect`
- `isinf`
- `isnan`
- `ldexp`
- `length`
- `lessThan`
- `lessThanEqual`
- `log`
- `log2`
- `matrixCompMult`
- `max`
- `memoryBarrier`
- `memoryBarrierAtomicCounter`
- `memoryBarrierBuffer`
- `memoryBarrierImage`
- `memoryBarrierShared`
- `min`
- `mix`
- `mod`
- `modf`
- `normalize`
- `not`
- `notEqual`
- `outerProduct`
- `packHalf2x16`
- `packSnorm2x16`
- `packSnorm4x8`
- `packUnorm2x16`
- `packUnorm4x8`
- `pow`
- `radians`
- `reflect`
- `refract`
- `round`
- `roundEven`
- `sign`
- `sin`
- `sinh`
- `smoothstep`
- `sqrt`
- `step`
- `struct`
- `tan`
- `tanh`
- `texelFetch`
- `texelFetchOffset`
- `texture`
- `textureGather`
- `textureGatherOffset`
- `textureGrad`
- `textureGradOffset`
- `textureLod`
- `textureLodOffset`
- `textureOffset`
- `textureProj`
- `textureProjGrad`
- `textureProjGradOffset`
- `textureProjLod`
- `textureProjLodOffset`
- `textureProjOffset`
- `textureSize`
- `transpose`
- `trunc`
- `uaddCarry`
- `uimage2DMSArray`
- `uintBitsToFloat`
- `umulExtended`
- `unpackHalf2x16`
- `unpackSnorm2x16`
- `unpackSnorm4x8`
- `unpackUnorm2x16`
- `unpackUnorm4x8`
- `usubBorrow`

### CODE REVIEW

**Comment by teoxoy** [comment]
Thanks for the PR!

While looking it over, I ended up checking the spec repo and documented where the keywords come from (also adding a few missing ones).

I also removed the ones starting with `gl_` since identifiers starting with that prefix are reserved according to the spec and also our current impl.

https://github.com/gfx-rs/naga/blob/5f8e4f6dead465f43b9727f151fa773770d6b488/src/back/glsl/mod.rs#L493

**Comment by teoxoy** [comment]
Let me know if it looks good, and we can land it.

**Comment by teoxoy** [comment]
Related: We should be renaming identifiers containing two consecutive underscores (see https://github.com/gfx-rs/naga/issues/2412).

**Comment by fornwall** [comment]
@teoxoy Looks good to me, nice work with the references!

> I also removed the ones starting with gl_ since identifiers starting with that prefix are reserved according to the spec and also our current impl.

Aha, didn't know that, thanks for the pointer!

**Pull request merged**
