### PR TITLE
Support 16-bit unorm/snorm formats

### PR DESCRIPTION
**Pull request by fintelia**
This PR adds handling for 16-bit unorm and snorm formats.

After making a few tweaks to wgpu, I was able to use this patch to load and run several GLSL compute shaders operating on r16 unorm textures. I haven't tested the other frontends/backends but the code I added mirrors the existing cases, so there's a good chance they should behave properly

### CODE REVIEW

**Comment by jimblandy** [comment]
This looks interesting, but before I review in detail:

We can't unconditionally extend WGSL, since that affects Firefox's implementation of the WebGPU standard, and we'd introduce incompatibilities between browsers. This probably needs to be conditional on some new flag in `naga::valid::Capabilities`.

**Review by teoxoy — APPROVED** [review]
LGTM, but could you also add them to the SPV front-end?

**Review by jimblandy — APPROVED** [review]
@teoxoy points out that #2161 covers making the non-WebGPU formats we already support in the WGSL front end conditional, and that's in milestone 4. So I think this is fine to merge as it is.

**Comment by teoxoy** [comment]
Sorry, I approved it without reading the comments properly.

I thought https://github.com/gfx-rs/naga/issues/2161 would cover this and could be done in a separate PR since there are a bunch of other formats. But ideally this PR should close https://github.com/gfx-rs/naga/issues/2162 (we don't yet have the framework for naga specific extensions but we can move that point from the issue into https://github.com/gfx-rs/naga/issues/2155).

@fintelia adding the `Capability` would be appreciated since we have to wire it to wgpu as well.

**Review by teoxoy — COMMENTED** [review]
Thanks for introducing the new capability!
Could you also add the new formats to the spv front-end?

**Pull request merged**
