### PR TITLE
spv-out: use OpFRem instead of OpFMod

### LINKED ISSUE #1652: WGSL float % translates into incorrect spirv op code
**Description**
WGSL spec says:
> Floating point remainder, where sign of non-zero result matches sign of e1. Component-wise when T is a vector.
> Result equal to: e1 - e2 * trunc(e1 / e2)
> (OpFRem)

While looking at the shader code in RenderDoc when using Vulkan backend I can see that the modulo operation was translated to:
> float _95 = FMod(_92, _94);

**Repro steps**
Use float % operator in WGSL shader where the first argument is a negative value. 

**Expected vs observed behavior**
The result of the % operation should be a negative value, but it is a positive value, because OpFMod is used instead of OpFRem.

**Platform**
Using wgpu 0.12.0 on Linux (Arch linux if it matters).

### PR DESCRIPTION
**Pull request by JCapucho**
Closes #1652

### CODE REVIEW

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
Looks like indexmap broke MSRV

**Comment by kvark** [comment]
Would you mind specifying indexmap dependency as "1.7"?

**Comment by JCapucho** [comment]
Sorry only noticed now.

But I'm confused we have in the `Cargo.toml`
```
indexmap = "1.6" # 1.7 has MSRV 1.49
```

why is it pulling `1.8` and how would changing it to `1.7` help?

**Comment by kvark** [comment]
Damn, hmm, interesting. Technically 1.8 is compatible with 1.6 that we are requesting. We need to request it differently:
```toml
indexmap = "~1.6"
```

**Comment by JCapucho** [comment]
It's fixed now

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
Published in naga-0.8.2

**Pull request merged**
