### PR TITLE
[msl-out][spv-out][glsl-out] Implement `ArraySize` on globals.

### PR DESCRIPTION
**Pull request by jimblandy**
Remaining work:
- [x] HLSL

### CODE REVIEW

**Review by kvark — COMMENTED** [review]
LGTM so far

**Comment by jimblandy** [comment]
(My SPIR-V was using the wrong id, too...)

**Comment by jimblandy** [comment]
looking at macOS

**Review by kvark — APPROVED** [review]
beautiful!

**Pull request merged**
