### PR TITLE
[msl-out] Fix gradient sampling typo

### PR DESCRIPTION
**Pull request by scoopr**
Found and tested on `rend3` dev branch cube sample

### CODE REVIEW

**Comment by scoopr** [comment]
Feels like there should be a test for this, but I'm not quite sure what and where.

**Comment by scoopr** [comment]
Oh, and cc @cwfitzgerald  ;)

**Review by kvark — APPROVED** [review]
oh nice!

**Comment by kvark** [comment]
Included in v0.6.1

**Pull request merged**
