### PR TITLE
[spv-in] Remove the cast from `parse_image_query_size`

### PR DESCRIPTION
**Pull request by expenses**
Would close https://github.com/gfx-rs/naga/issues/2354. See https://github.com/gfx-rs/naga/issues/2354#issuecomment-1563665811. This fixes the issue with my shaders (see https://github.com/gfx-rs/naga/issues/2354) but it might break others. Testing is probably important.

### CODE REVIEW

**Comment by expenses** [comment]
Hmm, looks like the translation to glsl is invalid: https://github.com/gfx-rs/naga/pull/2357/commits/d2368a09b7546b1078df36cb42de00c99ca2724a#diff-932c2e40d7cfd7c549ead1917747c2d1ebf86471f59ca9a90f2a96e154ab063c.

**Comment by evahop** [comment]
So I believe these casts existed because the wgsl equivalents will always be unsized. if spir-v can have both signed and unsigned integers this will still need to be casted for signed ints when targeting wgsl and unfortunately will be a little redundant for other targets unless we could be conditional based off the desired target.

**Comment by evahop** [comment]
Looks like `parse_image_query_other` also contains the same cast.

**Review by teoxoy — CHANGES_REQUESTED** [review]
Thanks for the PR! 

See https://github.com/gfx-rs/naga/issues/2354#issuecomment-1570374587 for the correct fix.

**Pull request closed without merging**
