### PR TITLE
Relicense under MIT+Apache2

### PR DESCRIPTION
**Pull request by kvark**
It's been requested in other projects:
  - https://github.com/gfx-rs/gfx/issues/847
  - https://github.com/kvark/copyless/issues/16

Requesting contributor's permission to change the license. Please leave a comment saying if you approve or reject this:
- [x] @kvark 
- [x] @Napokue 
- [x] @JCapucho 
- [x] @GabrielMajeri 
- [x] @pjoe 
- [x] @paulkernfeld 
- [x] @msiglreith 
- [x] @grovesNL 
- [x] @Skepfyr

### CODE REVIEW

**Comment by Napokue** [comment]
Sure no problem for me, glad to give my permission.

**Comment by JCapucho** [comment]
For me it's also okay

**Comment by msiglreith** [comment]
Fine for me

**Comment by paulkernfeld** [comment]
I approve 👍

**Comment by grovesNL** [comment]
Sounds good to me :+1:

**Comment by GabrielMajeri** [comment]
Approve :+1:

**Comment by pjoe** [comment]
👍

**Comment by Skepfyr** [comment]
I'm fine with this change too.

**Comment by kvark** [comment]
Thanks everyone!

**Pull request merged**
