### PR TITLE
build(cli): use conventional `bin` path for `naga-cli`

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Any particular reason for this?

**Comment by ErichDonGubler** [comment]
@cwfitzgerald: Good question! Context: It was an easy change, so I thought filing a PR first would be more interesting for discussion than trying another avenue for consensus first. This is mostly a bikeshed/yak shave, and I'd feel no sadness if this got closed on basis of everybody being comfortable with current configuration, or just waited for discussion.

The reasoning for this change is philosophical. I think it's more consistent with DX in the overall Rust ecosystem; that is, using the `bin` folder embraces Cargo's convention-over-configuration approach more fully. It keeps the naming of `naga-cli`'s output local to the binary's entry point. As a Rustacean of several years, I generally expect the vast majority of use cases with a single `bin` target to be covered by `src/main.rs` and/or the `src/bin/` folder, since there's no need for granularity with settings like `required-features`.

**Comment by teoxoy** [comment]
According to https://doc.rust-lang.org/cargo/guide/project-layout.html, `src/main.rs` should be the location of the default executable and work without the extra config in `Cargo.toml`. Maybe we should only remove the extra config in `Cargo.toml`?

**Comment by cwfitzgerald** [comment]
src/main.rs will end up with an executable named `naga-cli`, not `naga`, which we want.

**Comment by teoxoy** [comment]
Ah, I see. Because the name of the package is `naga-cli`.

I'm neutral on this change.

**Review by jimblandy — APPROVED** [review]
This seems to have no effect on the visible behavior, since the entry point file is renamed to `src/bin/naga.rs` - it just uses file names instead of `Config.toml` settings. Seems good to me.

**Pull request merged**
