### PR TITLE
[glsl-out] Es: convert 1D images to 2D

### PR DESCRIPTION
**Pull request by JCapucho**
glsl es doesn't support 1d samplers so they must be converted to 2d samplers and the respective operations on them patched.

### CODE REVIEW

**Review by kvark — APPROVED** [review]
Looks reasonable, thank you!
We might want to consolidate the checks a little bit better. There is a number of places doing 
`if coord_dim == 1 && self.options.version.is_es()`

**Comment by JCapucho** [comment]
@kvark I've rebased the PR and cleaned it up, but it seems like msl doesn't support offsets for 1d images and that trips up the CI.

**Comment by kvark** [comment]
@JCapucho sampling 1D with an offset is not a part of WGSL spec:
https://gpuweb.github.io/gpuweb/wgsl/#texturesample

So we need to remove this from "image.wgsl" out into some "image-ext.wgsl" potentially, or not test this at all

**Comment by JCapucho** [comment]
@kvark I've removed it for now.

Is this something we want to support (sampling with offset for 1d texutes)? if so do you want me to open an issue for msl or otherwise a issue for validation.

**Comment by kvark** [comment]
We'd probably want to have it at some point, but it feels super low priority. Unless you have a use case, that is :)
If/when we do this, we'll add a validation capability for this, and check accordingly.

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
We'll need wgpu-hal collaboration here

**Pull request merged**
