### PR TITLE
Handle empty variable names in namer

### LINKED ISSUE #1483: [wgsl-out] Certain SPIR-V Patterns Cause Invalid Accesses
When converting from spirv generated from the following glsl, the wgsl backend generates invalid code.

This is the the relevant snippet of the glsl:

```glsl
// Line 33
layout(set = 2, binding = 10) uniform TextureData {
    CPUMaterialData material;
};

void main() {
	// Line 47
	vec2 coords = vec2(material.uv_transform0 * vec3(i_coords0, 1.0));
}
```

Generates the following snippet of wgsl:

```wgsl
// Line 18
[[block]]
struct TextureData {
    material: CPUMaterialData;
};

[[group(2), binding(10)]]
// BUG: uniform with no name
var<uniform> : TextureData;

fn main1() {
	// line 36
	// BUG: invalid name before the .
	let e28: mat3x3<f32> = .material.uv_transform0;
}
```

Attached is the full glsl, spirv, spirv-dis, and wgsl generated. Conversion from glsl -> spirv done with glslc, spirv -> wgsl done with master naga.

[naga-bug.zip](https://github.com/gfx-rs/naga/files/7420503/naga-bug.zip)

I have assigned this as a wgsl-out backend issue, but could also be a spv-in issue.

### PR DESCRIPTION
**Pull request by Gordon-F**
Fix #1483

### CODE REVIEW

**Comment by jimblandy** [comment]
The test case in this PR passes even without the patch. The unnamed `uniform` has a name of `None`, and `Namer::reset` supplies "global" as the fallback in that case.

**Comment by jimblandy** [comment]
The `.spv` file provided in #1483 does trigger the bug, though.

**Comment by jimblandy** [comment]
The fix in the PR, however, is correct: the SPIR-V file provokes a call like this:

```
call_or(Some(""), "global") -> ""
```

The `Some("")` case is exactly what the PR handles.

It's just the test case that is ineffectual.

**Comment by Gordon-F** [comment]
> The test case in this PR passes even without the patch. The unnamed `uniform` has a name of `None`, and `Namer::reset` supplies `"global"` as the fallback in that case.

Yes, you are right, thank you. It's because `glsl-in` parse empty name as `None`, but `spv-in` parse as `Some("")`. I will make a PR with spv test instead of glsl.

**Comment by kvark** [comment]
Published in 0.7.2

**Pull request merged**
