### PR TITLE
Don't output identifiers starting with _

### PR DESCRIPTION
**Pull request by JCapucho**
Follow up to #1390 

Changes the bake prefix to `NAGA_e` instead of `_e` and adds a check to the namer, most of the changes are test outputs.

This is needed because wgsl doesn't allow identifiers starting with _

### CODE REVIEW

**Comment by kvark** [comment]
this is somewhat unfortunate. The code littered with NAGA doesn't look nearly as good.
How about just `e`?

**Comment by JCapucho** [comment]
@kvark updated the PR to use `e`

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
Can we limit this to WGSL-out only? It seems to me that "_e" is still better for backends that allow it.

**Comment by JCapucho** [comment]
Sure I was just reusing the code that was already there, but I can add a wgsl-out only bake prefix

**Comment by kvark** [comment]
Let's do it. Thank you!

**Comment by JCapucho** [comment]
@kvark done

**Review by kvark — APPROVED** [review]
thank you!

**Pull request merged**
