### PR TITLE
[glsl-out] Fix statement indentation

### PR DESCRIPTION
**Pull request by Gordon-F**
Fix readability of output GLSL shaders

### CODE REVIEW

**Review by kvark — APPROVED** [review]
Thank you!

**Comment by Gordon-F** [comment]
@kvark CI should be happy after last commit.

**Comment by kvark** [comment]
@Gordon-F sorry about this! I'm fixing it in #544 now, please revert this commit here

**Comment by Gordon-F** [comment]
@kvark Done 😄

**Pull request merged**
