### PR TITLE
When writing snapshots, reliably identify which writer has failed.

### PR DESCRIPTION
**Pull request by jimblandy**
This implements @kvark's suggestion in his review of #1384.

### CODE REVIEW

**Review by kvark — COMMENTED** [review]
Do you see any advantage of doing this versus just `printf`?
I think having `unwrap` in testing infrastructure is actually better than propagating errors up, since we get stack traces.

**Comment by jimblandy** [comment]
> Do you see any advantage of doing this versus just printf?

I thought about that, but then I thought the test output would get really long - number of files x number of output forms.

Backtraces are nice, but ideally they should point at the spot where the error was thrown - that's what I always want to know, anyway. The very popular `anyhow` crate seems to be the new standard, and it supports capturing backtraces when errors are created.

**Comment by kvark** [comment]
> I thought about that, but then I thought the test output would get really long - number of files x number of output forms.

Prints from tests are only actually emitted on failure, unless you explicitly ask for them. So with `println!` by default you get exactly zero noise. The extra info only shows up when stuff goes wrong.

**Comment by jimblandy** [comment]
Okay, this version just adds some printfs.

**Review by kvark — APPROVED** [review]
thanks!

**Pull request merged**
