### PR TITLE
Add view_index wgsl builtin

### PR DESCRIPTION
**Pull request by LaylBongers**
This builtin isn't part of the specification, but is a simple addition to add multi-view support for WGSL. Is there an extension mechanism we can make use of here? I'm too unfamiliar with WGSL what the best approach here is to take.

Related to: https://github.com/gfx-rs/wgpu/issues/2186

### CODE REVIEW

**Comment by LaylBongers** [comment]
Given that this is already behind a `Capability`, maybe this should be fine anyways, I'll take it off draft status.

**Review by kvark — APPROVED** [review]
Might as well put it into `src/back/wgsl/` too?

**Comment by LaylBongers** [comment]
Updated the commit so it's added to the backend for WGSL as well

**Comment by kvark** [comment]
Last question, is this really going to be a "view" index? Or could it be more specifically a "layer" index instead?

**Comment by LaylBongers** [comment]
The feature this maps to in OpenGL and Vulkan is specifically called "view index". For example this is `gl_ViewIndex` in GLSL. It works only with the "multiview" feature.

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
Published in 0.7.3

**Pull request merged**
