### PR TITLE
[hlsl-out] Implement all parts required by quad-spv snaphost test

### PR DESCRIPTION
**Pull request by Gordon-F**
Still draft, because I don't know why `dxc` segfault on output shader.

### CODE REVIEW

**Comment by kvark** [comment]
Looks like it doesn't like the `[]` things. Changing the initializers to these make it work:
```
float _expr13[1] = perVertexStruct.gl_ClipDistance;
float _expr14[1] = perVertexStruct.gl_CullDistance;
    
```

**Comment by Gordon-F** [comment]
Seems like we should use other tactics to handle gl_PerVertex for `hlsl-out`. We should avoid array writing for `gl_ClipDistance` and `gl_CullDistance` and write it as floatN (where N number of access to array).

So, for example:
```glsl
#version 450

struct gl_PerVertex
{
    vec4 gl_Position;
    float gl_ClipDistance[6];
} inStruct;


void main() {
    inStruct.gl_Position = vec4(1.0, 1.0, 1.0, 1.0);
    inStruct.gl_ClipDistance[0] = 0.0f;
    inStruct.gl_ClipDistance[1] = 0.0f;
    inStruct.gl_ClipDistance[2] = 0.0f;
    inStruct.gl_ClipDistance[3] = 0.0f;
    inStruct.gl_ClipDistance[4] = 0.0f;
    inStruct.gl_ClipDistance[5] = 0.0f;
}
```

```hlsl
struct SPIRV_Cross_Output
{
    float4 gl_Position : SV_Position;
    float4 gl_ClipDistance0 : SV_ClipDistance0;
    float2 gl_ClipDistance1 : SV_ClipDistance1;
};
```

Output shader should be like this:
```hlsl
struct gl_PerVertex {
    float4 gl_Position : SV_Position;
    float gl_PointSize : PSIZE;
    float gl_ClipDistance : SV_ClipDistance0;
    float gl_CullDistance : SV_CullDistance0;
};

struct type10 {
    float2 member : LOC0;
    float4 gl_Position1 : SV_Position;
    float gl_PointSize1 : PSIZE;
    float gl_ClipDistance1 : SV_ClipDistance0;
    float gl_CullDistance1 : SV_CullDistance0;
};

static float2 v_uv;
static float2 a_uv;
static gl_PerVertex perVertexStruct = { float4(0.0, 0.0, 0.0, 1.0), 1.0, float(0.0), float(0.0) };
static float2 a_pos;

struct VertexInput {
    float2 a_uv2 : LOC1;
    float2 a_pos2 : LOC0;
};

void main()
{
    float2 _expr12 = a_uv;
    v_uv = _expr12;
    float2 _expr13 = a_pos;
    perVertexStruct.gl_Position = float4(_expr13.x, _expr13.y, 0.0, 1.0);
    return;
}

type10 vert_main(VertexInput vertexinput)
{
    a_uv = vertexinput.a_uv2;
    a_pos = vertexinput.a_pos2;
    main();
    float2 _expr10 = v_uv;
    float4 _expr11 = perVertexStruct.gl_Position;
    float _expr12 = perVertexStruct.gl_PointSize;
    float _expr13 = perVertexStruct.gl_ClipDistance;
    float _expr14 = perVertexStruct.gl_CullDistance;
    const type10 type10_ = { _expr10, _expr11, _expr12, _expr13, _expr14 };
    return type10_;
}
```

gl_PerVertex really painful thing for 3 backends....

**Comment by Gordon-F** [comment]
@kvark Currently I'm not planning to do fix all problems with `ClipDistance` and `CullDistance`, so, I decided to workaround it and move further. It's not a big problem I guess, since it affected only `spv-in` path.

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
CI not happy

**Comment by Gordon-F** [comment]
> Looks like it doesn't like the [] things. Changing the initializers to these make it work:

Oh, all this time I think that I'm already tried your solution. But I was wrong. It would be better and easier just to write `[1]`, since we know array size at this step.

**Comment by Gordon-F** [comment]
@kvark Ready to merge. Thank you!

**Comment by Gordon-F** [comment]
Ooops, not ready, sorry.

**Review by kvark — APPROVED** [review]

**Pull request merged**
