### PR TITLE
[glsl-in] add support for array variables

### PR DESCRIPTION
**Pull request by mockersf**
I tried uncommenting the first line in https://github.com/gfx-rs/naga/blob/9cd6fd9c205a57824644d0baedc6c15997be1e36/tests/parse.rs#L39-L44 and fixed the first failure

This PR add parsing for https://github.com/gfx-rs/naga/blob/9cd6fd9c205a57824644d0baedc6c15997be1e36/tests/cases/glsl_constant_expression.vert#L5

### CODE REVIEW

**Review by kvark — APPROVED** [review]
please make clippy happy :)

**Comment by mockersf** [comment]
done!

**Comment by kvark** [comment]
> I tried uncommenting the first line in 

Is it still failing with this PR?

**Comment by mockersf** [comment]
seems https://github.com/gfx-rs/naga/blob/9cd6fd9c205a57824644d0baedc6c15997be1e36/tests/cases/glsl_constant_expression.vert#L8
automatically adds an arg to the function: https://github.com/gfx-rs/naga/blob/9cd6fd9c205a57824644d0baedc6c15997be1e36/src/front/glsl/variables.rs#L19

but not completely and that makes it fail. I'm not yet up to what's happening there, will try to fix it next

**Pull request merged**
