### PR TITLE
[glsl-in] consolidate tests

### PR DESCRIPTION
**Pull request by pjoe**
- remove simple lex test as was covered by others
- combine related tests to single function
- remove redundant prefix in test names

### CODE REVIEW

**Comment by pjoe** [comment]
@kvark though that does make the test code a bit cleaner, I don't like the way failures are then reported at the line number in the `sub_test` function, instead of at a specific 'instance' where a comparison fails. What do you think?

**Comment by pjoe** [comment]
Not really sure I understand, how this would change things?

**Comment by kvark** [comment]
> I don't like the way failures are then reported at the line number in the sub_test function

If we put `[track_caller]` I was thinking that the assert will report the line number of the caller, which is the `sub_test`. Anyhow, this can be addressed by just returning a `Result` in `sub_test`, so we don't need the fancy stuff.

**Comment by pjoe** [comment]
Ok, so the remaining question is more about asserts in loops vs. pointing to individual line.

Keeping them individual:
- pro: will point failures to specific instance
- con: will require a bit more code, for each token to verify

**Comment by pjoe** [comment]
As en example here is how failure looks with individual assert:
image

**Comment by kvark** [comment]
Seems fine to me. Are you concerned about this look?

**Comment by pjoe** [comment]
No, this is the way it looks with individual asserts (like currently). In terms of how failures are reported, this is how I'd prefer.

I'll try adding similar screenshot tomorrow for the other solution with a helper function, looping over expected tokens, and returning a `Result`

**Comment by kvark** [comment]
Just to clarify, reducing the number of `#[test]` functions does not mean having less asserts.

**Comment by pjoe** [comment]
Right, as it stands the PR reduces number of lexer test functions  to 4, would you prefer it all the way down to 1?

The matter of number of asserts relates to using a common helper function to check against an array of expected tokens, instead of asserting them individually.

**Comment by pjoe** [comment]
As agreed on matrix, consolidated lex tests to a single function

**Review by kvark — APPROVED** [review]

**Pull request merged**
