### PR TITLE
WIP add support for parsing Op::AtomicLoad in spv frontend

### PR DESCRIPTION
**Pull request by schell**
@cwfitzgerald here is my first stab at making progress on gfx-rs/wgpu#4489. Am I on the right track? Are there more steps besides parsing?

### CODE REVIEW

**Comment by schell** [comment]
I see here I provided a body that might match `OpAtomicLoad`, not `OpAtomicIAdd`...

**Comment by schell** [comment]
@Patryk27 Yes, that's exactly the situation as it stands. It's a really big bite to chew because of having to do that type-promotion. Here's the start of a conversation I had with the gang on the matrix channel (it's pretty long) https://app.element.io/#/room/#naga:matrix.org/$_04dSsaJ6O8BFPxfV61v6Wb9I8xYBy9Zrtm4nvF3PGs

**Comment by pema99** [comment]
You still attempting this or was it just a quick experiment?

**Comment by schell** [comment]
Just a quick experiment - I might pick it up again but if anyone else is going to give it a shot I'll defer.

**Comment by pema99** [comment]
Alright. I'd love to see this come to fruition, but I read a bit up on what is preventing it (the whole untyped atomics vs Atomic<T> thing), and the need for some kind of inference/promotion pass from regular to atomic types seems a bit... daunting for a first time contributor.

**Comment by pema99** [comment]
In case anyone reads this and is wondering what I am referring to: https://github.com/gpuweb/gpuweb/issues/2377

**Comment by cwfitzgerald** [comment]
Hello, thank you for your PR against Naga!

As part of https://github.com/gfx-rs/wgpu/issues/4231, we have moved development of Naga into the wgpu repository in the Naga subfolder. We have transferred all issues, but we are unable to automatically transfer PRs. 

As such, please recreate your PR against the wgpu repository. We apologize for the inconvenience this causes, but will make contributing to both projects more streamlined going forward.

We are leaving PRs open, but once they are transferred, please close the original Naga PR.

**Comment by schell** [comment]
I will retarget my PR at wgpu, thanks :)

**Pull request closed without merging**
