### PR TITLE
[glsl-out] Handle initializers for locals

### PR DESCRIPTION
**Pull request by kristoff3r**
This pretty trivial change unfortunately required a loop to mutably borrow both
`builder` and `manager` at the same time, so I had to separate them. Perhaps a
cleaner solution would be to use an object with internal state instead of free
functions.

### CODE REVIEW

**Review by JCapucho — COMMENTED** [review]
Thanks for the PR but there might be an issue here, the initialiser might refer to a local which hasn't been declared yet

**Comment by kristoff3r** [comment]
> Thanks for the PR but there might be an issue here, the initialiser might refer to a local which hasn't been declared yet

Ah, I didn't realize that was allowed. In that case I guess we need to do a topological sort first?

**Comment by JCapucho** [comment]
> > Thanks for the PR but there might be an issue here, the initialiser might refer to a local which hasn't been declared yet
> 
> Ah, I didn't realize that was allowed. In that case I guess we need to do a topological sort first?

The way I was thinking doing it was to write the local declaration

```
Type name;
```

And then write the initialiser

```
name = initialiser;
```

But now I'm not sure if a sort would be faster

**Comment by kvark** [comment]
It could be a design choice for the IR to require that the local variable initializers can only depend on previous local vars.
I guess we should check what SPIR-V requires in that sense.

**Comment by kvark** [comment]
Actually, it may be possible only in SPIRV frontend, and it makes no benefit to the backends.
So let's just enforce this at the IR level, so GLSL backend can expect these to be ordered already.

**Comment by kvark** [comment]
Actually actually, this isn't possible in SPIR-V either:
> Initializer must be an <id> from a constant instruction or a global (module scope) OpVariable instruction.

So a local can't be initialized with the value of another local. So we are all good :)

**Review by kvark — APPROVED** [review]

**Pull request merged**
