### PR TITLE
Fix typo in an error message

### PR DESCRIPTION
**Pull request by maku693**
Fixed a typo.

### CODE REVIEW

**Review by jimblandy — APPROVED** [review]
Thanks!

**Comment by jimblandy** [comment]
There's nothing actually wrong with this PR; the CI failure is caused by #1752. I'll land that separately, and then restart this.

**Comment by jimblandy** [comment]
Since "allow edits" wasn't enabled on this PR, I couldn't rebase this, so I created #1753 for this change, rebased on #1752. Your name still appears in the commit message.

**Comment by maku693** [comment]
Ah, sorry about that. Thank you for recreating PR!

**Pull request closed without merging**
